try:
    result = 45/0
except:
    print('Error Occured')
finally:
    print('Done')